// Films shown this season, shared by every page (carousel, programme list
// and the per-film detail page at film.html).
//
// Edit this list to change the line-up. Each entry needs:
//   id       — unique slug (the film's Letterboxd slug works well); used in
//              the film.html?id=... URL and to key stored reviews
//   poster   — a local poster image in images/
//   date     — screening date, ISO format (films[0] opens the season)
//   url      — the film's Letterboxd page
// The remaining fields (director, runtime, genres, synopsis, blurb,
// content) appear on the film's detail page.
const FILMS = [
  {
    id: "the-godfather",
    title: "The Godfather",
    year: 1972,
    date: "2026-08-27",
    poster: "images/the-godfather.jpg",
    url: "https://letterboxd.com/film/the-godfather/",
    director: "Francis Ford Coppola",
    runtime: 175,
    genres: ["Crime", "Drama"],
    synopsis: "The aging patriarch of an organised-crime dynasty transfers control of his clandestine empire to his reluctant youngest son.",
    blurb: "We open the season with the greatest of them all. Come for Brando, stay for the coffee.",
    content: "Strong violence",
  },
  {
    id: "spirited-away",
    title: "Spirited Away",
    year: 2001,
    date: "2026-09-03",
    poster: "images/spirited-away.jpg",
    url: "https://letterboxd.com/film/spirited-away/",
    director: "Hayao Miyazaki",
    runtime: 125,
    genres: ["Animation", "Fantasy", "Adventure"],
    synopsis: "A sullen ten-year-old girl wanders into a world ruled by gods, witches and spirits, where humans are changed into beasts.",
    blurb: "Animation night! Miyazaki's Oscar-winner on the big screen — bring a friend who hasn't seen it.",
    content: "Family friendly",
  },
  {
    id: "interstellar",
    title: "Interstellar",
    year: 2014,
    date: "2026-09-10",
    poster: "images/interstellar.jpg",
    url: "https://letterboxd.com/film/interstellar/",
    director: "Christopher Nolan",
    runtime: 169,
    genres: ["Sci-Fi", "Adventure", "Drama"],
    synopsis: "With Earth's resources failing, a former pilot leads a team of researchers through a newly discovered wormhole in search of a habitable planet.",
    blurb: "Nolan's space epic with the loudest organ in cinema. Best enjoyed big and loud.",
  },
  {
    id: "whiplash-2014",
    title: "Whiplash",
    year: 2014,
    date: "2026-09-17",
    poster: "images/whiplash.jpg",
    url: "https://letterboxd.com/film/whiplash-2014/",
    director: "Damien Chazelle",
    runtime: 106,
    genres: ["Drama", "Music"],
    synopsis: "A promising young drummer enrolls at a cut-throat music conservatory, where his dreams of greatness are mentored by an instructor who will stop at nothing to realise a student's potential.",
    blurb: "Not quite my tempo. Two knockout performances and a final scene you'll be talking about all the way home.",
    content: "Strong language",
  },
  {
    id: "blade-runner-2049",
    title: "Blade Runner 2049",
    year: 2017,
    date: "2026-09-24",
    poster: "images/blade-runner-2049.jpg",
    url: "https://letterboxd.com/film/blade-runner-2049/",
    director: "Denis Villeneuve",
    runtime: 164,
    genres: ["Sci-Fi", "Drama"],
    synopsis: "A new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what's left of society into chaos.",
    blurb: "Neon, rain and Roger Deakins' Oscar-winning cinematography — modern sci-fi built for the big screen.",
    content: "Violence, nudity",
  },
  {
    id: "la-la-land",
    title: "La La Land",
    year: 2016,
    date: "2026-10-01",
    poster: "images/la-la-land.jpg",
    url: "https://letterboxd.com/film/la-la-land/",
    director: "Damien Chazelle",
    runtime: 128,
    genres: ["Musical", "Romance", "Drama"],
    synopsis: "An aspiring actress and a dedicated jazz musician struggle to make ends meet while pursuing their dreams in a city known for destroying hopes and breaking hearts.",
    blurb: "Musicals night — sing along at your own risk. Here's to the ones who dream.",
  },
  {
    id: "inception",
    title: "Inception",
    year: 2010,
    date: "2026-10-08",
    poster: "images/inception.jpg",
    url: "https://letterboxd.com/film/inception/",
    director: "Christopher Nolan",
    runtime: 148,
    genres: ["Sci-Fi", "Action", "Thriller"],
    synopsis: "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    blurb: "A heist inside the mind. Bring your own spinning top.",
    content: "Violence",
  },
  {
    id: "fight-club",
    title: "Fight Club",
    year: 1999,
    date: "2026-10-15",
    poster: "images/fight-club.jpg",
    url: "https://letterboxd.com/film/fight-club/",
    director: "David Fincher",
    runtime: 139,
    genres: ["Drama", "Thriller"],
    synopsis: "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
    blurb: "Season finale. First rule: tell everyone about film night. Stick around afterwards for our end-of-term chat.",
    content: "Strong violence",
  },
];
